name: bioinformatics-talk
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - black
  - jupyterlab_code_formatter
  - pandas
  - numpy
  - networkx
  - matplotlib
  - gensim
  - scikit-learn
  - pip:
    - deepwalk
    - node2vec
